
export const lhcBallList = [
    { text: "01", shape: "", odds: "", color: "red", dx: "", ds: "" },
    { text: "02", shape: "", odds: "", color: "red", dx: "", ds: "" },
    { text: "03", shape: "", odds: "", color: "blue", dx: "", ds: "" },
    { text: "04", shape: "", odds: "", color: "blue", dx: "", ds: "" },
    { text: "05", shape: "", odds: "", color: "green", dx: "", ds: "" },
    { text: "06", shape: "", odds: "", color: "green", dx: "", ds: "" },
    { text: "07", shape: "", odds: "", color: "red", dx: "", ds: "" },
    { text: "08", shape: "", odds: "", color: "red", dx: "", ds: "" },
    { text: "09", shape: "", odds: "", color: "blue", dx: "", ds: "" },
    { text: "10", shape: "", odds: "", color: "blue", dx: "", ds: "" },
    { text: "11", shape: "", odds: "", color: "green", dx: "", ds: "" },
    { text: "12", shape: "", odds: "", color: "red", dx: "", ds: "" },
    { text: "13", shape: "", odds: "", color: "red", dx: "", ds: "" },
    { text: "14", shape: "", odds: "", color: "blue", dx: "", ds: "" },
    { text: "15", shape: "", odds: "", color: "blue", dx: "", ds: "" },
    { text: "16", shape: "", odds: "", color: "green", dx: "", ds: "" },
    { text: "17", shape: "", odds: "", color: "green", dx: "", ds: "" },
    { text: "18", shape: "", odds: "", color: "red", dx: "", ds: "" },
    { text: "19", shape: "", odds: "", color: "red", dx: "", ds: "" },
    { text: "20", shape: "", odds: "", color: "blue", dx: "", ds: "" },
    { text: "21", shape: "", odds: "", color: "green", dx: "", ds: "" },
    { text: "22", shape: "", odds: "", color: "green", dx: "", ds: "" },
    { text: "23", shape: "", odds: "", color: "red", dx: "", ds: "" },
    { text: "24", shape: "", odds: "", color: "red", dx: "", ds: "" },
    { text: "25", shape: "", odds: "", color: "blue", dx: "", ds: "" },
    { text: "26", shape: "", odds: "", color: "blue", dx: "", ds: "" },
    { text: "27", shape: "", odds: "", color: "green", dx: "", ds: "" },
    { text: "28", shape: "", odds: "", color: "green", dx: "", ds: "" },
    { text: "29", shape: "", odds: "", color: "red", dx: "", ds: "" },
    { text: "30", shape: "", odds: "", color: "red", dx: "", ds: "" },
    { text: "31", shape: "", odds: "", color: "blue", dx: "", ds: "" },
    { text: "32", shape: "", odds: "", color: "green", dx: "", ds: "" },
    { text: "33", shape: "", odds: "", color: "green", dx: "", ds: "" },
    { text: "34", shape: "", odds: "", color: "red", dx: "", ds: "" },
    { text: "35", shape: "", odds: "", color: "red", dx: "", ds: "" },
    { text: "36", shape: "", odds: "", color: "blue", dx: "", ds: "" },
    { text: "37", shape: "", odds: "", color: "blue", dx: "", ds: "" },
    { text: "38", shape: "", odds: "", color: "green", dx: "", ds: "" },
    { text: "39", shape: "", odds: "", color: "green", dx: "", ds: "" },
    { text: "40", shape: "", odds: "", color: "red", dx: "", ds: "" },
    { text: "41", shape: "", odds: "", color: "blue", dx: "", ds: "" },
    { text: "42", shape: "", odds: "", color: "blue", dx: "", ds: "" },
    { text: "43", shape: "", odds: "", color: "green", dx: "", ds: "" },
    { text: "44", shape: "", odds: "", color: "green", dx: "", ds: "" },
    { text: "45", shape: "", odds: "", color: "red", dx: "", ds: "" },
    { text: "46", shape: "", odds: "", color: "red", dx: "", ds: "" },
    { text: "47", shape: "", odds: "", color: "blue", dx: "", ds: "" },
    { text: "48", shape: "", odds: "", color: "blue", dx: "", ds: "" },
    { text: "49", shape: "", odds: "", color: "green", dx: "", ds: "" },
]

export const shengxiaoList = [
    { text: "鼠", shape: "rect", mutex: "", odds: "", color: "", dx: "", ds: "" },
    { text: "牛", shape: "rect", mutex: "", odds: "", color: "", dx: "", ds: "" },
    { text: "虎", shape: "rect", mutex: "", odds: "", color: "", dx: "", ds: "" },
    { text: "兔", shape: "rect", mutex: "", odds: "", color: "", dx: "", ds: "" },
    { text: "龙", shape: "rect", mutex: "", odds: "", color: "", dx: "", ds: "" },
    { text: "蛇", shape: "rect", mutex: "", odds: "", color: "", dx: "", ds: "" },
    { text: "马", shape: "rect", mutex: "", odds: "", color: "", dx: "", ds: "" },
    { text: "羊", shape: "rect", mutex: "", odds: "", color: "", dx: "", ds: "" },
    { text: "猴", shape: "rect", mutex: "", odds: "", color: "", dx: "", ds: "" },
    { text: "鸡", shape: "rect", mutex: "", odds: "", color: "", dx: "", ds: "" },
    { text: "狗", shape: "rect", mutex: "", odds: "", color: "", dx: "", ds: "" },
    { text: "猪", shape: "rect", mutex: "", odds: "", color: "", dx: "", ds: "" },
]

export const dxdsBallList = [
    { text: "大", shape: "circle", mutex: "dx", odds: "", color: "", dx: "大", ds: "" },
    { text: "小", shape: "circle", mutex: "dx", odds: "", color: "", dx: "小", ds: "" },
    { text: "单", shape: "circle", mutex: "ds", odds: "", color: "", dx: "", ds: "单" },
    { text: "双", shape: "circle", mutex: "ds", odds: "", color: "", dx: "", ds: "双" },
];