const config = {
  "3": {
    id: "3",
    name: "香港⑥合彩",
    logo: "LHC",
    type: "lhc",
    type2: "六合彩",
    betApi: "Six/Bet",
    betListApi: "Six/GetBetList",
    drawHistoryApi: "Six/GetLotterys",
    typeOrder: 1,
    drawLive: true,
    delay_tms: 300000,
  },
  "10": {
    id: "10",
    name: "新加坡⑥合彩",
    logo: "LHCSG",
    type: "lhc",
    type2: "六合彩",
    betApi: "Six/Bet",
    betListApi: "Six/GetBetList",
    drawHistoryApi: "Six/GetLotterys",
    typeOrder: 3,
    delay_tms: 300000,
  },
  "18": {
    id: "18",
    name: "台湾⑥合彩",
    logo: "LHCTW",
    type: "lhc",
    type2: "六合彩",
    betApi: "Six/Bet",
    betListApi: "Six/GetBetList",
    drawHistoryApi: "Six/GetLotterys",
    typeOrder: 4,
    delay_tms: 300000,
  },
  //预设澳门
  "21": {
    id: "21",
    name: "新澳门⑥合彩",
    logo: "LHCMACAU",
    type: "lhc",
    type2: "六合彩",
    betApi: "Six/Bet",
    betListApi: "Six/GetBetList",
    drawHistoryApi: "Six/GetLotterys",
    typeOrder: 2,
    drawLive: true,
    delay_tms: 900000,
  },
  "31": {
    id: "31",
    name: "三分⑥合彩",
    logo: "LHC3",
    type: "lhc",
    type2: "极速彩",
    betApi: "Six/Bet",
    betListApi: "Six/GetBetList",
    drawHistoryApi: "Six/GetLotterys",
    typeOrder: 8,
    delay_tms: 60000,
  },
  "37": {
    id: "37",
    name: "五分⑥合彩",
    logo: "LHC5",
    type: "lhc",
    type2: "极速彩",
    betApi: "Six/Bet",
    betListApi: "Six/GetBetList",
    drawHistoryApi: "Six/GetLotterys",
    typeOrder: 9,
    delay_tms: 60000,
  },

  "42": {
    id: "42",
    name: "一分⑥合彩",
    logo: "LHC1",
    type: "lhc",
    type2: "极速彩",
    betApi: "Six/Bet",
    betListApi: "Six/GetBetList",
    drawHistoryApi: "Six/GetLotterys",
    typeOrder: 7,
    delay_tms: 60000,
  },

  specific: ["3", "21"],
}
export default config
