export default [
  { name: "游戏大厅", img: "file/pg/lobby.png", width: 100, gameCode: "pgsoft_0" },

  { name: "麻将胡了", img: "https://img.dyn123.com/images/slot-images/PGsoft/mahjongways.png", width: 33, gameCode: "pgsoft_65" },
  { name: "麻将胡了2", img: "https://img.dyn123.com/images/slot-images/PGsoft/mahjongways2.png", width: 33, gameCode: "pgsoft_74" },
  { name: "赏金女王", img: "https://img.dyn123.com/images/slot-images/PGsoft/queenofbounty.png", width: 33, gameCode: "pgsoft_84" },
  { name: "赏金大对决", img: "https://img.dyn123.com/images/slot-images/PGsoft/wildbountyshowdown.png", width: 33, gameCode: "pgsoft_135" },
  { name: "寻宝黄金城", img: "https://img.dyn123.com/images/slot-images/PGsoft/treasuresofaztec.png", width: 33, gameCode: "pgsoft_87" },
  { name: "少林足球", img: "https://img.dyn123.com/images/slot-images/PGsoft/shaolinsoccer.png", width: 33, gameCode: "pgsoft_67" },

  { name: "三只疯狂小猪", img: "https://img.dyn123.com/images/slot-images/PGsoft/threecrazypiggies.png", width: 33, gameCode: "pgsoft_1727711" },
  { name: "南美之翼", img: "https://img.dyn123.com/images/slot-images/PGsoft/wingsofiguazu.png", width: 33, gameCode: "pgsoft_1747549" },
  { name: "江山美景图", img: "https://img.dyn123.com/images/slot-images/PGsoft/orientalprosperity.png", width: 33, gameCode: "pgsoft_112" },
  { name: "星旅淘金", img: "https://img.dyn123.com/images/slot-images/PGsoft/galacticgems.png", width: 33, gameCode: "pgsoft_86" },

  { name: "极道荣耀", img: "https://img.dyn123.com/images/slot-images/PGsoft/yakuzahonor.png", width: 33, gameCode: "pgsoft_yakuzahonor" },
  { name: "鲨鱼猎手 (鲨鱼赏金)", img: "https://img.dyn123.com/images/slot-images/PGsoft/sharkhunter.png", width: 33, gameCode: "pgsoft_1648578" },
  { name: "小鸡跑酷", img: "https://img.dyn123.com/images/slot-images/PGsoft/chickyrun.png", width: 33, gameCode: "pgsoft_1738001" },
  { name: "热血足球", img: "https://img.dyn123.com/images/slot-images/PGsoft/futebolfever.png", width: 33, gameCode: "pgsoft_1778752" },
  { name: "丧尸危机", img: "https://img.dyn123.com/images/slot-images/PGsoft/zombieoutbreak.png", width: 33, gameCode: "pgsoft_1635221" },
  { name: "阿努比斯", img: "https://img.dyn123.com/images/slot-images/PGsoft/anubiswrath.png", width: 33, gameCode: "pgsoft_1623475" },
  { name: "魔法药水", img: "https://img.dyn123.com/images/slot-images/PGsoft/mysticpotion.png", width: 33, gameCode: "pgsoft_1717688" },
  { name: "墨西哥狂欢", img: "https://img.dyn123.com/images/slot-images/PGsoft/pinatawins.png", width: 33, gameCode: "pgsoft_1492288" },
  { name: "猿宇宙#3258", img: "https://img.dyn123.com/images/slot-images/PGsoft/wildape233258.png", width: 33, gameCode: "pgsoft_1508783" },
  { name: "快钱来了", img: "https://img.dyn123.com/images/slot-images/PGsoft/cashmania.png", width: 33, gameCode: "pgsoft_1682240" },
  { name: "黑帮风云", img: "https://img.dyn123.com/images/slot-images/PGsoft/mafiamayhem.png", width: 33, gameCode: "pgsoft_1580541" },
  { name: "沙皇宝藏", img: "https://img.dyn123.com/images/slot-images/PGsoft/tsartreasures.png", width: 33, gameCode: "pgsoft_1655268" },
  { name: "宝石矿工 ", img: "https://img.dyn123.com/images/slot-images/PGsoft/gemstonesgold.png", width: 33, gameCode: "pgsoft_1671262" },
  { name: "金龙送宝", img: "https://img.dyn123.com/images/slot-images/PGsoft/fortunedragon.png", width: 33, gameCode: "pgsoft_1695365" },
  { name: "寻龙探宝 2", img: "https://img.dyn123.com/images/slot-images/PGsoft/dragonhatch2.png", width: 33, gameCode: "pgsoft_1451122" },
  { name: "狼人传奇", img: "https://img.dyn123.com/images/slot-images/PGsoft/werewolfshunt.png", width: 33, gameCode: "pgsoft_1615454" },

  { name: "铸造大师", img: "https://img.dyn123.com/images/slot-images/PGsoft/forgeofwealth.png", width: 33, gameCode: "pgsoft_1555350" },
  { name: "怪盗神偷", img: "https://img.dyn123.com/images/slot-images/PGsoft/wildheistcashout.png", width: 33, gameCode: "pgsoft_1568554" },
  { name: "金球射手", img: "https://img.dyn123.com/images/slot-images/PGsoft/ultimatestriker.png", width: 33, gameCode: "pgsoft_1489936" },
  { name: "忍者小浣熊", img: "https://img.dyn123.com/images/slot-images/PGsoft/ninjaraccoonfrenzy.png", width: 33, gameCode: "pgsoft_1529867" },
  { name: "角斗士荣耀", img: "https://img.dyn123.com/images/slot-images/PGsoft/gladiatorsglory.png", width: 33, gameCode: "pgsoft_1572362" },
  { name: "非洲大冒险", img: "https://img.dyn123.com/images/slot-images/PGsoft/safariwilds.png", width: 33, gameCode: "pgsoft_1594259" },
  { name: "幸运草之恋", img: "https://img.dyn123.com/images/slot-images/PGsoft/luckycloverlady.png", width: 33, gameCode: "pgsoft_1601012" },
  { name: "皇家游轮", img: "https://img.dyn123.com/images/slot-images/PGsoft/cruiseroyale.png", width: 33, gameCode: "pgsoft_1473388" },
  { name: "水果甜心", img: "https://img.dyn123.com/images/slot-images/PGsoft/fruitycandy.png", width: 33, gameCode: "pgsoft_1397455" },
  { name: "超级高尔夫", img: "https://img.dyn123.com/images/slot-images/PGsoft/supergolfdrive.png", width: 33, gameCode: "pgsoft_1513328" },
  { name: "元素精灵", img: "https://img.dyn123.com/images/slot-images/PGsoft/mysticalspirits.png", width: 33, gameCode: "pgsoft_1432733" },
  { name: "泰嗨泼水节", img: "https://img.dyn123.com/images/slot-images/PGsoft/songkransplash.png", width: 33, gameCode: "pgsoft_1448762" },
  { name: "烘焙总动员", img: "https://img.dyn123.com/images/slot-images/PGsoft/bakerybonanza.png", width: 33, gameCode: "pgsoft_1418544" },
  { name: "夏威夷探奇", img: "https://img.dyn123.com/images/slot-images/PGsoft/hawaiiantiki.png", width: 33, gameCode: "pgsoft_1381200" },
  { name: "电音派对", img: "https://img.dyn123.com/images/slot-images/PGsoft/ravepartyfever.png", width: 33, gameCode: "pgsoft_1420892" },
  { name: "金钱兔", img: "https://img.dyn123.com/images/slot-images/PGsoft/fortunerabbit.png", width: 33, gameCode: "pgsoft_1543462" },
  { name: "点石成金", img: "https://img.dyn123.com/images/slot-images/PGsoft/midasfortune.png", width: 33, gameCode: "pgsoft_1402846" },
  { name: "维京纪元", img: "https://img.dyn123.com/images/slot-images/PGsoft/asgardianrising.png", width: 33, gameCode: "pgsoft_1340277" },
  { name: "炼金工坊", img: "https://img.dyn123.com/images/slot-images/PGsoft/alchemygold.png", width: 33, gameCode: "pgsoft_1368367" },
  { name: "图腾奇迹", img: "https://img.dyn123.com/images/slot-images/PGsoft/totemwonders.png", width: 33, gameCode: "pgsoft_1338274" },
  { name: "斗鸡", img: "https://img.dyn123.com/images/slot-images/PGsoft/roosterrumble.png", width: 33, gameCode: "pgsoft_123" },
  { name: "美食美刻", img: "https://img.dyn123.com/images/slot-images/PGsoft/dinerdelights.png", width: 33, gameCode: "pgsoft_1372643" },
  { name: "黄金摇钱树", img: "https://img.dyn123.com/images/slot-images/PGsoft/prosperityfortunetree.png", width: 33, gameCode: "pgsoft_1312883" },
  {
    name: "双赢鱼虾蟹",
    img: "https://img.dyn123.com/images/slot-images/PGsoft/winwinfishprawncrab.png",
    width: 33,
    gameCode: "pgsoft_129",
  },
  { name: "野生杯垫", img: "https://img.dyn123.com/images/slot-images/PGsoft/wildcoaster.png", width: 33, gameCode: "pgsoft_132" },

  { name: "王后的宴会", img: "https://img.dyn123.com/images/slot-images/PGsoft/thequeensbanquet.png", width: 33, gameCode: "pgsoft_120" },
  { name: "速度赢家", img: "https://img.dyn123.com/images/slot-images/PGsoft/speedwinner.png", width: 33, gameCode: "pgsoft_127" },
  { name: "幸运小猪", img: "https://img.dyn123.com/images/slot-images/PGsoft/luckypiggy.png", width: 33, gameCode: "pgsoft_130" },
  { name: "珀尔修斯传说", img: "https://img.dyn123.com/images/slot-images/PGsoft/legendofperseus.png", width: 33, gameCode: "pgsoft_128" },
  { name: "蝴蝶花开", img: "https://img.dyn123.com/images/slot-images/PGsoft/butterflyblossom.png", width: 33, gameCode: "pgsoft_125" },
  { name: "皇家战场", img: "https://img.dyn123.com/images/slot-images/PGsoft/battlegroundroyale.png", width: 33, gameCode: "pgsoft_124" },
  { name: "神鹰宝石", img: "https://img.dyn123.com/images/slot-images/PGsoft/garudagems.png", width: 33, gameCode: "pgsoft_122" },
  { name: "日月星辰", img: "https://img.dyn123.com/images/slot-images/PGsoft/destinyofsunandmoon.png", width: 33, gameCode: "pgsoft_121" },
  { name: "假面嘉年华", img: "https://img.dyn123.com/images/slot-images/PGsoft/maskcarnival.png", width: 33, gameCode: "pgsoft_118" },
  { name: "虎虎生财", img: "https://img.dyn123.com/images/slot-images/PGsoft/fortunetiger.png", width: 33, gameCode: "pgsoft_126" },
  { name: "夜醉佳人", img: "https://img.dyn123.com/images/slot-images/PGsoft/cocktailnights.png", width: 33, gameCode: "pgsoft_117" },
  { name: "爱尔兰精灵", img: "https://img.dyn123.com/images/slot-images/PGsoft/leprechaunriches.png", width: 33, gameCode: "pgsoft_60" },

  { name: "鱼跃龙门", img: "https://img.dyn123.com/images/slot-images/PGsoft/dragonlegend.png", width: 33, gameCode: "pgsoft_29" },
  { name: "钞级表情包", img: "https://img.dyn123.com/images/slot-images/PGsoft/emojiriches.png", width: 33, gameCode: "pgsoft_114" },
  { name: "皇上吉祥", img: "https://img.dyn123.com/images/slot-images/PGsoft/emperorsfavour.png", width: 33, gameCode: "pgsoft_44" },
  { name: "唐伯虎点秋香", img: "https://img.dyn123.com/images/slot-images/PGsoft/flirtingscholar.png", width: 33, gameCode: "pgsoft_61" },
  { name: "横财来啦", img: "https://img.dyn123.com/images/slot-images/PGsoft/fortunegods.png", width: 33, gameCode: "pgsoft_3" },
  { name: "鼠鼠福福", img: "https://img.dyn123.com/images/slot-images/PGsoft/fortunemouse.png", width: 33, gameCode: "pgsoft_68" },
  { name: "象财神", img: "https://img.dyn123.com/images/slot-images/PGsoft/ganeshagold.png", width: 33, gameCode: "pgsoft_42" },
  { name: "宝石侠", img: "https://img.dyn123.com/images/slot-images/PGsoft/gemsaviour.png", width: 33, gameCode: "pgsoft_2" },
  { name: "宝石侠 - 宝藏征途", img: "https://img.dyn123.com/images/slot-images/PGsoft/gemsaviourconquest.png", width: 33, gameCode: "pgsoft_62" },
  { name: "宝石侠-大宝剑", img: "https://img.dyn123.com/images/slot-images/PGsoft/gemsavioursword.png", width: 33, gameCode: "pgsoft_38" },
  { name: "阿拉丁神灯", img: "https://img.dyn123.com/images/slot-images/PGsoft/genie3wishes.png", width: 33, gameCode: "pgsoft_85" },
  { name: "冰火双娇", img: "https://img.dyn123.com/images/slot-images/PGsoft/guardiansofice.png", width: 33, gameCode: "pgsoft_91" },
  { name: "嘻哈熊猫", img: "https://img.dyn123.com/images/slot-images/PGsoft/hiphoppanda.png", width: 33, gameCode: "pgsoft_33" },
  { name: "夜戏貂蝉", img: "https://img.dyn123.com/images/slot-images/PGsoft/honeytrapofdiaochan.png", width: 33, gameCode: "pgsoft_1" },
  { name: "逆袭的小红帽", img: "https://img.dyn123.com/images/slot-images/PGsoft/hoodvswolf.png", width: 33, gameCode: "pgsoft_18" },
  { name: "麻辣火锅", img: "https://img.dyn123.com/images/slot-images/PGsoft/hotpot.png", width: 33, gameCode: "pgsoft_28" },
  { name: "冰锋奇侠", img: "https://img.dyn123.com/images/slot-images/PGsoft/jackfrostswinter.png", width: 33, gameCode: "pgsoft_97" },
  { name: "金玉满堂", img: "https://img.dyn123.com/images/slot-images/PGsoft/jewelsofprosperity.png", width: 33, gameCode: "pgsoft_88" },
  { name: "嘻游记", img: "https://img.dyn123.com/images/slot-images/PGsoft/journeytothewealth.png", width: 33, gameCode: "pgsoft_50" },
  { name: "水果丛林", img: "https://img.dyn123.com/images/slot-images/PGsoft/jungledelight.png", width: 33, gameCode: "pgsoft_40" },
  { name: "恐龙帝国", img: "https://img.dyn123.com/images/slot-images/PGsoft/jurassickingdom.png", width: 33, gameCode: "pgsoft_110" },
  { name: "美猴王传奇", img: "https://img.dyn123.com/images/slot-images/PGsoft/legendarymonkeyking.png", width: 33, gameCode: "pgsoft_107" },
  { name: "后羿射日", img: "https://img.dyn123.com/images/slot-images/PGsoft/legendofhouyi.png", width: 33, gameCode: "pgsoft_34" },
  { name: "宝石传奇", img: "https://img.dyn123.com/images/slot-images/PGsoft/majestictreasures.png", width: 33, gameCode: "pgsoft_95" },
  { name: "美杜莎 ", img: "https://img.dyn123.com/images/slot-images/PGsoft/medusa.png", width: 33, gameCode: "pgsoft_7" },
  { name: "美杜莎 II", img: "https://img.dyn123.com/images/slot-images/PGsoft/medusaii.png", width: 33, gameCode: "pgsoft_6" },
  { name: "人鱼公主", img: "https://img.dyn123.com/images/slot-images/PGsoft/mermaidriches.png", width: 33, gameCode: "pgsoft_102" },
  { name: "冰雪大冲关", img: "https://img.dyn123.com/images/slot-images/PGsoft/thegreaticescape.png", width: 33, gameCode: "pgsoft_53" },
  { name: "福运象财神", img: "https://img.dyn123.com/images/slot-images/PGsoft/ganeshafortune.png", width: 33, gameCode: "pgsoft_75" },
  { name: "龙虎争霸", img: "https://img.dyn123.com/images/slot-images/PGsoft/dragontigerluck.png", width: 33, gameCode: "pgsoft_63" },
  { name: "美洲野牛", img: "https://img.dyn123.com/images/slot-images/PGsoft/buffalowin.png", width: 33, gameCode: "pgsoft_108" },
  { name: "欢乐嘉年华", img: "https://img.dyn123.com/images/slot-images/PGsoft/circusdelight.png", width: 33, gameCode: "pgsoft_80" },
  { name: "糖果连连爆", img: "https://img.dyn123.com/images/slot-images/PGsoft/candyburst.png", width: 33, gameCode: "pgsoft_70" },
  { name: "糖心风暴", img: "https://img.dyn123.com/images/slot-images/PGsoft/candybonanza.png", width: 33, gameCode: "pgsoft_100" },
  { name: "比基尼天堂", img: "https://img.dyn123.com/images/slot-images/PGsoft/bikiniparadise.png", width: 33, gameCode: "pgsoft_69" },

  { name: "霹雳神偷", img: "https://img.dyn123.com/images/slot-images/PGsoft/heiststakes.png", width: 33, gameCode: "pgsoft_105" },
  { name: "舞狮进宝", img: "https://img.dyn123.com/images/slot-images/PGsoft/prosperitylion.png", width: 33, gameCode: "pgsoft_36" },
  { name: "比特淘金", img: "https://img.dyn123.com/images/slot-images/PGsoft/cryptogold.png", width: 33, gameCode: "pgsoft_103" },
  { name: "巴厘之旅", img: "https://img.dyn123.com/images/slot-images/PGsoft/balivacation.png", width: 33, gameCode: "pgsoft_94" },
  { name: "水上泰神奇", img: "https://img.dyn123.com/images/slot-images/PGsoft/thairiverwonders.png", width: 33, gameCode: "pgsoft_92" },
  { name: "火树赢花", img: "https://img.dyn123.com/images/slot-images/PGsoft/wildfireworks.png", width: 33, gameCode: "pgsoft_83" },
  { name: "凤凰传奇", img: "https://img.dyn123.com/images/slot-images/PGsoft/phoenixrises.png", width: 33, gameCode: "pgsoft_82" },
  { name: "埃及探秘宝典 ", img: "https://img.dyn123.com/images/slot-images/PGsoft/egyptsbookofmystery.png", width: 33, gameCode: "pgsoft_73" },
  { name: "寻龙探宝", img: "https://img.dyn123.com/images/slot-images/PGsoft/dragonhatch.png", width: 33, gameCode: "pgsoft_57" },
  { name: "麒麟送宝", img: "https://img.dyn123.com/images/slot-images/PGsoft/waysoftheqilin.png", width: 33, gameCode: "pgsoft_106" },
  { name: "亡灵大盗", img: "https://img.dyn123.com/images/slot-images/PGsoft/wildbandito.png", width: 33, gameCode: "pgsoft_104" },
  { name: "十倍金牛", img: "https://img.dyn123.com/images/slot-images/PGsoft/fortuneox.png", width: 33, gameCode: "pgsoft_98" },

  { name: "澳门壕梦", img: "https://img.dyn123.com/images/slot-images/PGsoft/dreamsofmacau.png", width: 33, gameCode: "pgsoft_79" },
  { name: "赢财神", img: "https://img.dyn123.com/images/slot-images/PGsoft/caishenwins.png", width: 33, gameCode: "pgsoft_71" },
  { name: "赏金船长", img: "https://img.dyn123.com/images/slot-images/PGsoft/captainsbounty.png", width: 33, gameCode: "pgsoft_54" },
  { name: "双囍临门", img: "https://img.dyn123.com/images/slot-images/PGsoft/doublefortune.png", width: 33, gameCode: "pgsoft_48" },
  { name: "招财喵", img: "https://img.dyn123.com/images/slot-images/PGsoft/luckyneko.png", width: 33, gameCode: "pgsoft_89" },

  { name: "旺旺旺", img: "https://img.dyn123.com/images/slot-images/PGsoft/winwinwon.png", width: 33, gameCode: "pgsoft_24" },
  { name: "万胜狂欢夜", img: "https://img.dyn123.com/images/slot-images/PGsoft/mrhallowwin.png", width: 33, gameCode: "pgsoft_35" },
  { name: " 德古拉女爵", img: "https://img.dyn123.com/images/slot-images/PGsoft/vampirescharm.png", width: 33, gameCode: "pgsoft_58" },
  { name: "摇钱树", img: "https://img.dyn123.com/images/slot-images/PGsoft/treeoffortune.png", width: 33, gameCode: "pgsoft_26" },
  { name: "埃及寻宝", img: "https://img.dyn123.com/images/slot-images/PGsoft/symbolsofegypt.png", width: 33, gameCode: "pgsoft_41" },
  { name: "超市大血拼", img: "https://img.dyn123.com/images/slot-images/PGsoft/supermarketspree.png", width: 33, gameCode: "pgsoft_115" },

  { name: " 艳后之谜", img: "https://img.dyn123.com/images/slot-images/PGsoft/secretsofcleopatra.png", width: 33, gameCode: "pgsoft_90" },
  { name: "圣诞欢乐送", img: "https://img.dyn123.com/images/slot-images/PGsoft/santasgiftrush.png", width: 33, gameCode: "pgsoft_37" },
  { name: "太阳神传说", img: "https://img.dyn123.com/images/slot-images/PGsoft/riseofapollo.png", width: 33, gameCode: "pgsoft_101" },
  {
    name: "丽影奇兵之探秘埃及",
    img: "https://img.dyn123.com/images/slot-images/PGsoft/raidersjanecryptoffortune.png",
    width: 33,
    gameCode: "pgsoft_113",
  },
  { name: "亲爱的", img: "https://img.dyn123.com/images/slot-images/PGsoft/reellove.png", width: 33, gameCode: "pgsoft_20" },
  { name: "抓抓乐", img: "https://img.dyn123.com/images/slot-images/PGsoft/plushiefrenzy.png", width: 33, gameCode: "pgsoft_25" },
  { name: "金猪报财", img: "https://img.dyn123.com/images/slot-images/PGsoft/piggygold.png", width: 33, gameCode: "pgsoft_39" },
  { name: "新国粹", img: "https://img.dyn123.com/images/slot-images/PGsoft/operadynasty.png", width: 33, gameCode: "pgsoft_93" },
  { name: "忍者vs武侍", img: "https://img.dyn123.com/images/slot-images/PGsoft/ninjavssamurai.png", width: 33, gameCode: "pgsoft_59" },
  { name: "拳霸", img: "https://img.dyn123.com/images/slot-images/PGsoft/muaythaichampion.png", width: 33, gameCode: "pgsoft_64" },
  { name: "日月星辰", img: "https://img.dyn123.com/images/slot-images/PGsoft/destinyofsunandmoon.png", width: 33, gameCode: "pgsoft_121" },
  { name: "虎虎生财", img: "https://img.dyn123.com/images/slot-images/PGsoft/fortunetiger.png", width: 33, gameCode: "pgsoft_126" },
  { name: "神鹰宝石", img: "https://img.dyn123.com/images/slot-images/PGsoft/garudagems.png", width: 33, gameCode: "pgsoft_122" },
  { name: "夜醉佳人", img: "https://img.dyn123.com/images/slot-images/PGsoft/cocktailnights.png", width: 33, gameCode: "pgsoft_117" },
  { name: "假面嘉年华", img: "https://img.dyn123.com/images/slot-images/PGsoft/maskcarnival.png", width: 33, gameCode: "pgsoft_118" },

  // { name: "百鬼夜行", img: "https://img.dyn123.com/images/slot-images/PGsoft/spiritedwonders.png", width: 33, gameCode: "pgsoft_119" },
  // { name: "星际农场", img: "https://img.dyn123.com/images/slot-images/PGsoft/farminvaders.png", width: 33, gameCode: "pgsoft_116" },
  // { name: "寿司之道", img: "https://img.dyn123.com/images/slot-images/PGsoft/sushioishi.png", width: 33, gameCode: "pgsoft_109" },
  // { name: "地鼠总动员", img: "https://img.dyn123.com/images/slot-images/PGsoft/groundhogharvest.png", width: 33, gameCode: "pgsoft_111" },
  // { name: "三只猴子", img: "https://img.dyn123.com/images/slot-images/PGsoft/3monkeys.png", width: 33, gameCode: "pgsoft_43" },
  // { name: "巫师之书", img: "https://img.dyn123.com/images/slot-images/PGsoft/wizdomwonders.png", width: 33, gameCode: "pgsoft_17" },
]
